use_frameworks!

platform :ios, '8.0'

target 'XLComProject_Example' do
  pod 'XLComProject', :path => '../'

  target 'XLComProject_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    
    pod 'AFNetworking'
    pod 'RegexKitLite'
    pod 'SDWebImage'
    #pod 'SDWebImage/WebP'
    pod 'SDWebImage/GIF'
    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'IQKeyboardManager'
#    pod 'WCDB'
    pod 'MJExtension'
    pod 'Reachability', '~> 3.2'
    pod 'TZImagePickerController'
  end
end
